{{- range .Values.deployments_name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "telemetry-demoapp.fullname" $ }}-{{ . }}
  labels:
    prometheus.io/scrape: "true"
    {{- include "telemetry-demoapp.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "telemetry-demoapp.name" $ }}-{{ . }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
---
{{- end }}
