# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "project" {
  type = string
}
variable "region" {
  type = string
}
variable "zone" {
  type = string
}
variable "clustername" {
  type = string
}
