name: Primary deployment

on:
  push:
    branches: master

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
     run:
       shell: bash
       working-directory: ./terraform

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
         terraform_version: 1.4.6
         terraform_wrapper: false

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/45727971247/locations/global/workloadIdentityPools/my-wi-pool/providers/provider1'
        service_account: 'terr-sa@myinfra1.iam.gserviceaccount.com'

    - name: Deploy
      id: deploy
      working-directory: ./terraform/deploy
      run: |
        terraform init 
        terraform apply -auto-approve -input=false
        echo "cluster_name=$(terraform output -raw cluster_name)" >> $GITHUB_OUTPUT
        echo "cluster_location=$(terraform output -raw cluster_location)" >> $GITHUB_OUTPUT

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: ${{steps.deploy.outputs.cluster_name}}
        location: ${{steps.deploy.outputs.cluster_location}}

    - name: ArgoCD
      working-directory: ./terraform/argocd
      run: |
        echo '${{ steps.deploy.outputs.stdout || steps.deploy.outputs.stderr }}'
        echo '${{ steps.deploy.outputs.cluster_name}}'
        terraform init 
        terraform apply -auto-approve -input=false

    - name: ArgoCD Application Set
      working-directory: .
      run: |
        kubectl apply -f appSet.yaml
