name: Primary deployment

on:
  push:
    branches: master

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
     run:
       shell: bash
       working-directory: ./terraform

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/45727971247/locations/global/workloadIdentityPools/my-wi-pool/providers/provider1'
        service_account: 'terr-sa@myinfra1.iam.gserviceaccount.com'

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
         terraform_version: 1.4.6


    - name: Terraform init
      run: terraform init 

    - name: Terraform validate
      run: terraform validate

    - name: Terraform plan
      run: terraform plan

    - name: Terraform apply
      run: terraform apply -auto-approve -input=false
