name: Primary deployment

on:
  push:
    branches: master

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
     run:
       shell: bash
       working-directory: ./terraform

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
         terraform_version: 1.4.6
         terraform_wrapper: false

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.1.0
      with:
        terragrunt_version: 0.39.2

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/45727971247/locations/global/workloadIdentityPools/my-wi-pool/providers/provider1'
        service_account: 'terr-sa@myinfra1.iam.gserviceaccount.com'

    - name: Deploy
      id: deploy
      working-directory: ./terraform
      run: |
        terragrunt init 
        terragrunt run-all apply --terragrunt-non-interactive
        echo "cluster_name=$(terraform output -raw cluster_name)" >> $GITHUB_OUTPUT
        echo "cluster_location=$(terraform output -raw cluster_location)" >> $GITHUB_OUTPUT

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: ${{steps.deploy.outputs.cluster_name}}
        location: ${{steps.deploy.outputs.cluster_location}}

    - name: ArgoCD Application Set
      working-directory: .
      run: |
        kubectl apply -f appSet.yaml

    - name: Build and push Docker image Telemetry Demo App
      working-directory: telemetry-demoapp
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev -q
        docker build . -t telemetry-demoapp:1.0.1
        docker tag telemetry-demoapp:1.0.1 us-central1-docker.pkg.dev/myinfra1/my-repository/telemetry-demoapp:1.0.1
        docker push us-central1-docker.pkg.dev/myinfra1/my-repository/telemetry-demoapp:1.0.1
